//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mangaed_projects
    {
        public int Id { get; set; }
        public int project_id { get; set; }
        public int pm_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime deliver_date { get; set; }
        public int cost { get; set; }
        public int state_id { get; set; }
    
        public virtual project project { get; set; }
        public virtual user user { get; set; }
        public virtual state state { get; set; }
    }
}
