//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database2Entities3 : DbContext
    {
        public Database2Entities3()
            : base("name=Database2Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<mangaed_projects> mangaed_projects { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<project_comments> project_comments { get; set; }
        public virtual DbSet<project_members> project_members { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_qualification> user_qualification { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
    }
}
