//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.feedbacks = new HashSet<feedback>();
            this.mangaed_projects = new HashSet<mangaed_projects>();
            this.project_comments = new HashSet<project_comments>();
            this.project_members = new HashSet<project_members>();
            this.requests = new HashSet<request>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int duration { get; set; }
        public int customer_id { get; set; }
        public int posting_state_id { get; set; }
        public int assigend_state_id { get; set; }
        public System.DateTime creation_date { get; set; }
    
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual ICollection<mangaed_projects> mangaed_projects { get; set; }
        public virtual ICollection<project_comments> project_comments { get; set; }
        public virtual ICollection<project_members> project_members { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
