//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.mangaed_projects = new HashSet<mangaed_projects>();
            this.requests = new HashSet<request>();
        }
    
        public int Id { get; set; }
        public string state1 { get; set; }
    
        public virtual ICollection<mangaed_projects> mangaed_projects { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
