//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.feedbacks = new HashSet<feedback>();
            this.feedbacks1 = new HashSet<feedback>();
            this.feedbacks2 = new HashSet<feedback>();
            this.mangaed_projects = new HashSet<mangaed_projects>();
            this.projects = new HashSet<project>();
            this.project_comments = new HashSet<project_comments>();
            this.project_members = new HashSet<project_members>();
            this.reports = new HashSet<report>();
            this.reports1 = new HashSet<report>();
            this.requests = new HashSet<request>();
            this.requests1 = new HashSet<request>();
            this.user_qualification = new HashSet<user_qualification>();
        }
    
        public int id { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phone_number { get; set; }
        public string jop_description { get; set; }
        public byte[] image { get; set; }
        public int type_id { get; set; }
    
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual ICollection<feedback> feedbacks1 { get; set; }
        public virtual ICollection<feedback> feedbacks2 { get; set; }
        public virtual ICollection<mangaed_projects> mangaed_projects { get; set; }
        public virtual ICollection<project> projects { get; set; }
        public virtual ICollection<project_comments> project_comments { get; set; }
        public virtual ICollection<project_members> project_members { get; set; }
        public virtual ICollection<report> reports { get; set; }
        public virtual ICollection<report> reports1 { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<request> requests1 { get; set; }
        public virtual ICollection<user_qualification> user_qualification { get; set; }
        public virtual user_type user_type { get; set; }
    }
}
